from __future__ import annotations

from typing import Optional

from ytmusicapi import YTMusic

from .cookies import cookies_to_header
from .session import AuthSession


def create(session: AuthSession, headers_auth_path: Optional[str] = None) -> YTMusic:
    """Builds a ytmusicapi client from an AuthSession.

    If YT_MUSIC_HEADERS_AUTH points at a headers_auth.json generated by
    `ytmusicapi browser`, that takes precedence — it's the most reliable path.

    Otherwise a headers dict is built from the cookie jar. ytmusicapi only treats
    a passed-in auth dict as "browser" (cookie) auth if it already contains an
    `authorization` header whose value contains "SAPISIDHASH" — the placeholder
    below exists purely to satisfy that check; ytmusicapi recomputes the real
    SAPISIDHASH per request from the `__Secure-3PAPISID` cookie (see
    ytmusicapi.helpers.get_authorization / sapisid_from_cookie).
    """
    if headers_auth_path:
        return YTMusic(auth=headers_auth_path, location=session.geographical_location)

    if not session.cookies:
        return YTMusic(location=session.geographical_location)

    headers = {
        "cookie": cookies_to_header(session.cookies),
        "origin": "https://music.youtube.com",
        "x-goog-authuser": "0",
        "authorization": "SAPISIDHASH",  # placeholder — recomputed per request, see above
    }
    return YTMusic(auth=headers, location=session.geographical_location)
